{% set version = "0.8-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-polycor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/polycor_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/polycor/polycor_{{ version }}.tar.gz
  sha256: f05f53e0b5c992de0e5b4c6b2e998148cf83310358821e1bba180d81face0509

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-admisc >=0.22
    - r-mvtnorm
  run:
    - r-base
    - r-matrix
    - r-admisc >=0.22
    - r-mvtnorm

test:
  commands:
    - $R -e "library('polycor')"           # [not win]
    - "\"%R%\" -e \"library('polycor')\""  # [win]

about:
  home: https://r-forge.r-project.org/projects/polycor/, https://CRAN.R-project.org/package=polycor
  license: GPL-2.0-or-later
  summary: Computes polychoric and polyserial correlations by quick "two-step" methods or ML, optionally with standard errors; tetrachoric and biserial correlations are special cases.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - jacodela

# Package: polycor
# Version: 0.7-10
# Date: 2019-07-22
# Title: Polychoric and Polyserial Correlations
# Authors@R: person("John", "Fox", role = c("aut", "cre"), email = "jfox@mcmaster.ca")
# Depends: R (>= 3.3.0)
# Imports: stats, mvtnorm, Matrix
# ByteCompile: yes
# LazyLoad: yes
# Description: Computes polychoric and polyserial correlations by quick "two-step" methods or ML, optionally with standard errors; tetrachoric and biserial correlations are special cases.
# License: GPL (>= 2)
# URL: https://r-forge.r-project.org/projects/polycor/, https://CRAN.R-project.org/package=polycor
# NeedsCompilation: no
# Packaged: 2019-08-05 17:37:42 UTC; jfox
# Author: John Fox [aut, cre]
# Maintainer: John Fox <jfox@mcmaster.ca>
# Repository: CRAN
# Date/Publication: 2019-08-05 18:40:02 UTC
