travis:
  secure:
    BINSTAR_TOKEN: UslhMKaoRtmxzAp/Pon5UTk8UWxcYQDedr9i7KhIV7J3cM8UEaE25A3zTfepGh/Qf6zTjQFzAlJRYAlWCthcrsML6ciJ6U+K8864HN7u44cTdybRULMV+t/QwFdo3DHNl6KHSN3N5WzeMcCCQ1VuJBI9xbLTnrC2LUMl/3AvE8xhM445My/QXHpIQqzHGQ2H/fbEuLR7DekdLudSoR89lSEFVCmRjpJqVDeLJ2cRWKt3qyUUkmveTgAFhYVfqTibnBLzt9t843+frWQDPUpsbgooaKmAx5Ubeaqj5FgBnuxp9rNcW2hIZxqwRCfgRy0BEdvIhc8yJ80Mjee/LlG1Hg7FL+7SdvJ/YYmztDOYvDtqkHUmAWnNsFspzt6pw0OI++O0zc8bNQOdNtijaYvZJ6zzNHunrzFSLWyHmfOAegRsq/ly4y9iJAptwcbJqb/4q3NFylWwAIGms2EJOt/lZdc/RBhrhHxm/Pld1pauraXYTqx/fWFeLKoIlKTwAiqVkhStjqdg8hcj/Nd6+OX7sa5eoK42pk8N4Es2OkBKARwJiwU078y48itMd44pWZO6tGDd1cFeqd3T7ulMcCZgOTp/ajc7MIaUoLDjKD9E24EYsyKwYGO3HO8kR8SyU09MT/Bo1+X5tTOWilRvvJGrldW9BYZ84DUfjP7Edz6VfjY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
